//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class approval
    {
        public approval() {}

        [Key]
        public int approval_id { get; set; }
        [Required]
        public Nullable<int> member_id { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> approval_date { get; set; }
    
        public virtual members members { get; set; }
        public virtual ICollection<data_file> data_file { get; set; }
        public virtual ICollection<hwm> hwms { get; set; }
    }
}
