//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class contact_type
    {
        public contact_type() { }

        [Key]
        public int contact_type_id { get; set; }
        [Required]
        public string type { get; set; }
    
        public virtual ICollection<reportmetric_contact> reportmetric_contact { get; set; }
    }
}
