//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class county
    {
        public county() { }

        [Key]
        public Nullable<int> county_fip { get; set; }
        [Required]
        public string county_name { get; set; }
        [Required]
        public Nullable<int> state_fip { get; set; }
        [ForeignKey ("state_fip")]
        public virtual states states { get; set; }
    }
}
