//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class county
    {
        public county() { }

        [Key]
        public int county_id { get; set; }
        [Required]//, RegularExpression()] // add Reg Exp to check that county name either ends with " Parish" or " County" , RegularExpression(@"\w * Id\b")] 
        public string county_name { get; set; }
        [Required]
        public int state_id { get; set; }
        [Required]
        public Nullable<int> state_fip { get; set; }
        [Required]
        public Nullable<int> county_fip { get; set; }
    
        public virtual states states { get; set; }
    }
}
