//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class data_file
    {
        public data_file() {}

        [Key]
        public int data_file_id { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> start { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> end { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> good_start { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> good_end { get; set; }
        [Required]
        public Nullable<int> processor_id { get; set; }
        [Required]
        public Nullable<int> instrument_id { get; set; }
        public Nullable<int> approval_id { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> collect_date { get; set; }
        public Nullable<int> peak_summary_id { get; set; }
        public string elevation_status { get; set; }
        public string time_zone { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> last_updated_by { get; set; }
    
        public virtual instrument instrument { get; set; }
        public virtual peak_summary peak_summary { get; set; }
        [ForeignKey("processor_id")]
        public virtual members members { get; set; }
        public virtual approval approval { get; set; }
        public virtual ICollection<file> files { get; set; }
    }
}
