//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class deployment_priority
    {
        public deployment_priority() {}

        [Key]
        public int priority_id { get; set; }
        [Required]
        public string priority_name { get; set; }
    
        public virtual ICollection<sites> sites { get; set; }
    }
}
