//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class events
    {
        public events() {}

        [Key]
        public int event_id { get; set; }
        [Required]
        public string event_name { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> event_start_date { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> event_end_date { get; set; }
        public string event_description { get; set; }
        [Required]
        public Nullable<int> event_type_id { get; set; }
        [Required]
        public Nullable<int> event_status_id { get; set; }
        [Required]
        public Nullable<int> event_coordinator { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> last_updated_by { get; set; }
    
        public virtual ICollection<instrument> instruments { get; set; }
        public virtual ICollection<hwm> hwms { get; set; }
        public virtual event_status event_status { get; set; }
        [ForeignKey("event_coordinator")]
        public virtual members members { get; set; }
        public virtual event_type event_type { get; set; }
    }
}
