//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class file_type
    {
        public file_type() {}

        [Key]
        public int filetype_id { get; set; }
        [Required]
        public string filetype { get; set; }
    
        public virtual ICollection<file> files { get; set; }
    }
}
