//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class hwm_qualities
    {
        public hwm_qualities() {}

        [Key]
        public int hwm_quality_id { get; set; }
        [Required]
        public string hwm_quality { get; set; }
        public Nullable<double> min_range { get; set; }
        public Nullable<double> max_range { get; set; }
    
        public virtual ICollection<hwm> hwms { get; set; }
    }
}
