//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class hwm_types
    {
        public hwm_types() {}

        [Key]
        public int hwm_type_id { get; set; }
        [Required]
        public string hwm_type { get; set; }
    
        public virtual ICollection<hwm> hwms { get; set; }
    }
}
