//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class instr_collection_conditions
    {
        public instr_collection_conditions() {}

        [Key]
        public int id { get; set; }
        [Required]
        public string condition { get; set; }
    
        public virtual ICollection<instrument> instruments { get; set; }
    }
}
