//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class members
    {
        public members() {}

        [Key]
        public int member_id { get; set; }
        [Required]
        public string fname { get; set; }
        [Required]
        public string lname { get; set; }
        [Required]
        public int agency_id { get; set; }
        [Required]
        public string phone { get; set; }
        [Required]
        public string email { get; set; }
        public string emergency_contact_name { get; set; }
        public string emergency_contact_phone { get; set; }
        [Required]
        public int role_id { get; set; }
        [Required]
        public string username { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public Nullable<int> resetFlag { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> last_updated_by { get; set; }
    
        public virtual agency agency { get; set; }
        public virtual roles roles { get; set; }
        public virtual ICollection<instrument_status> instrument_status { get; set; }
        public virtual ICollection<events> events { get; set; }
        public virtual ICollection<peak_summary> peak_summary { get; set; }
        public virtual ICollection<sites> sites { get; set; }
        public virtual ICollection<approval> approvals { get; set; }
        public virtual ICollection<data_file> data_file { get; set; }
        public virtual ICollection<hwm> flag_memberHWMs { get; set; }
        public virtual ICollection<hwm> survey_memberHWMs { get; set; }
    }
}
