//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class network_name_site
    {
        public network_name_site() { }

        [Key]
        public int networkname_site_id { get; set; }
        [Required]
        public int network_name_id { get; set; }
        [Required]
        public int site_id { get; set; }
    
        public virtual network_name network_name { get; set; }
        public virtual sites site { get; set; }
    }
}
