//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class network_type
    {
        public network_type() {}

        [Key]
        public int network_type_id { get; set; }
        [Required]
        public string network_type_name { get; set; }
    
        public virtual ICollection<network_type_site> network_type_site { get; set; }
    }
}
