//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class network_name
    {
        public network_name() {}

        [Key]
        public int network_name_id { get; set; }
        [Required]
        public string name { get; set; }
    
        public virtual ICollection<network_name_site> network_name_site { get; set; }
    }
}
