//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class objective_point_type
    {
        public objective_point_type() {}

        [Key]
        public int objective_point_type_id { get; set; }
        [Required]
        public string op_type { get; set; }
    
        public virtual ICollection<objective_point> objective_point { get; set; }
    }
}
