//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class op_control_identifier
    {
        public op_control_identifier() {}

        [Key]
        public int op_control_identifier_id { get; set; }
        [Required]
        public Nullable<int> objective_point_id { get; set; }
        [Required]
        public string identifier { get; set; }
        [Required]
        public string identifier_type { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> last_updated_by { get; set; }
    
        public virtual objective_point objective_point { get; set; }
    }
}
