//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class op_quality
    {
        public op_quality() {}

        [Key]
        public int op_quality_id { get; set; }
        [Required]
        public string quality { get; set; }
    
        public virtual ICollection<objective_point> objective_point { get; set; }
    }
}
