//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class reportmetric_contact
    {
        public reportmetric_contact() { }

        [Key]
        public int reportmetric_contact_id { get; set; }
        [Required]
        public int reporting_metrics_id { get; set; }
        [Required]
        public int contact_id { get; set; }
        [Required]
        public int contact_type_id { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> last_updated_by { get; set; }
    
        public virtual contact_type contact_type { get; set; }
        public virtual contact contact { get; set; }
        public virtual reporting_metrics reporting_metrics { get; set; }
    }
}
