//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class roles
    {
        public roles() {}

        [Key]
        public int role_id { get; set; }
        [Required]        
        public string role_name { get; set; }
        [Required]
        public string role_description { get; set; }
    
        public virtual ICollection<members> members { get; set; }
    }
}
