//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sensor_type
    {
        public sensor_type() {}

        [Key]
        public int sensor_type_id { get; set; }
        [Required]
        public string sensor { get; set; }
    
        public virtual ICollection<sensor_deployment> sensor_deployment { get; set; }
        public virtual ICollection<instrument> instruments { get; set; }
    }
}
