//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class site_housing
    {
        public site_housing() { }

        [Key]
        public int site_housing_id { get; set; }
        [Required]
        public Nullable<int> site_id { get; set; }
        [Required]
        public Nullable<int> housing_type_id { get; set; }
        public Nullable<double> length { get; set; }
        public string material { get; set; }
        public string notes { get; set; }
        [Required]
        public Nullable<double> amount { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> last_updated_by { get; set; }
    
        public virtual sites site { get; set; }
    }
}
