//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class sites
    {
        public sites() {}

        [Key]
        public int site_id { get; set; }
        [Required]
        public string site_no { get; set; }
        [Required]
        public string site_name { get; set; }
        [Required]
        public string site_description { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        [Required]
        public string state { get; set; }
        public string zip { get; set; }
        public string other_sid { get; set; }
        [Required]
        public string county { get; set; }
        [Required]
        public string waterbody { get; set; }
        [Required]
        public double latitude_dd { get; set; }
        [Required]
        public double longitude_dd { get; set; }
        [Required]
        public int hdatum_id { get; set; }
        public Nullable<double> drainage_area_sqmi { get; set; }
        public Nullable<int> landownercontact_id { get; set; }
        public Nullable<int> priority_id { get; set; }
        public string zone { get; set; }
        public string is_permanent_housing_installed { get; set; }
        public string usgs_sid { get; set; }
        public string noaa_sid { get; set; }
        [Required]
        public Nullable<int> hcollect_method_id { get; set; }
        public string site_notes { get; set; }
        public string safety_notes { get; set; }
        public string access_granted { get; set; }
        [Required]
        public Nullable<int> member_id { get; set; }
        public Nullable<int> sensor_not_appropriate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> last_updated { get; set; }
        public Nullable<int> last_updated_by { get; set; }
    
        public virtual ICollection<network_name_site> network_name_site { get; set; }
        public virtual ICollection<network_type_site> network_type_site { get; set; }
        public virtual ICollection<objective_point> objective_points { get; set; }
        [ForeignKey("hdatum_id")]
        public virtual horizontal_datums horizontal_datums { get; set; }
        public virtual deployment_priority deployment_priority { get; set; }
        [ForeignKey("landownercontact_id")]
        public virtual landownercontact landownercontact { get; set; }
        public virtual horizontal_collect_methods horizontal_collect_methods { get; set; }
        public virtual ICollection<instrument> instruments { get; set; }
        public virtual members members { get; set; }
        public virtual ICollection<file> files { get; set; }
        public virtual ICollection<site_housing> site_housing { get; set; }
        public virtual ICollection<hwm> hwms { get; set; }
    }
}
