//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class states
    {
        public states() {}

        [Key]
        public int state_id { get; set; }
        [Required]
        public string state_name { get; set; }
        [Required]
        public string state_abbrev { get; set; }
    
        public virtual ICollection<county> counties { get; set; }
    }
}
