//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vertical_datums
    {
        public vertical_datums() {}

        [Key]
        public int datum_id { get; set; }
        [Required]
        public string datum_name { get; set; }
        [Required]
        public string datum_abbreviation { get; set; }
    
        public virtual ICollection<objective_point> objective_point { get; set; }
        public virtual ICollection<instrument_status> instrument_status { get; set; }
        public virtual ICollection<peak_summary> peak_summary { get; set; }
        public virtual ICollection<hwm> hwms { get; set; }
    }
}
