//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STNDB.Resources
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class vertical_collect_methods
    {
        public vertical_collect_methods() {}

        [Key]
        public int vcollect_method_id { get; set; }
        [Required]
        public string vcollect_method { get; set; }
    
        public virtual ICollection<hwm> hwms { get; set; }
    }
}
